/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'web-toolbox',
  DESCRIPTION: "Collection of web developer utilities",
  VERSION: '4.0.0',
  VERSION_DATE: '2025-12-31',
});

export const LONG_VERSION_DATE = '4.0.0 (2025-12-31)';

