// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'web-toolbox',
  DESCRIPTION: 'Collection of web developer utilities',
  REPOSITORY: 'https://github.com/amwebexpert/etoolbox',
  AUTHOR: 'amwebexpert@gmail.com',
  VERSION: '4.0.0',
  VERSION_DATE: '2025-12-31',
  VERSION_DATE_ISO: '2025-12-31T22:22:02.427Z',
})

export const LONG_VERSION_DATE = '4.0.0 (2025-12-31)'
